parameters:
    kunstmaan_live_reload.script_injector.class: 'Kunstmaan\LiveReloadBundle\EventListener\ScriptInjectorListener'
    kunstmaan_live_reload.disable_cache.class: 'Kunstmaan\LiveReloadBundle\EventListener\DisableCacheListener'

services:
    kunstmaan_live_reload.script_injector:
        class: "%kunstmaan_live_reload.script_injector.class%"
        arguments: ["%kunstmaan_live_reload.host%", "%kunstmaan_live_reload.port%", "%kunstmaan_live_reload.enabled%"]
        tags:
            - { name: kernel.event_subscriber }

    kunstmaan_live_reload.disable_cache:
        class: "%kunstmaan_live_reload.disable_cache.class%"
        arguments: ["%kunstmaan_live_reload.enabled%"]
        tags:
            - { name: kernel.event_subscriber }